management:
  trace:
    http:
      enabled: false
  endpoints:
    web:
      base-path: /
      exposure:
        include: health,info

spring:
  jmx:
    enabled: false

logging:
  pattern:
    level: "%5p %X{}"

server:
  forward-headers-strategy: native